# Generated by Django 4.1.3 on 2022-11-16 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='estado',
            field=models.CharField(choices=[('RJ', 'RJ'), ('SP', 'SP'), ('MG', 'MG'), ('ES', 'ES')], max_length=2),
        ),
    ]
