# Generated by Django 4.1.3 on 2022-11-23 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_alter_pessoa_telefone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='rua',
        ),
    ]
